### ISSUE TITLE
Planned support for postgres? 

### ISSUE THREAD

**Issue by Braunson** [vcian/laravel-db-auditor#44]
Any planned support for postgres by chance?

**Comment by vrusua** [comment]
+1 please

**Comment by vc-urvin** [comment]
Thank you for your interest. We are planning to support PostgreSQL in the near future. 

Stay tuned for updates!

**Comment by ruchit288** [comment]
@Braunson and @vrusua - Now you can audit PostgreSQL DB using this Wonderful DB auditor.
Feel free to share if you find any issues and we are happy if you can contribute to this package and take it to the next level. :)
