### ISSUE TITLE
Lang error

### ISSUE THREAD

**Issue by emresasi** [vcian/laravel-db-auditor#47]
I'm getting this error in the suggestion(s) section.

Lang::messages.standard.error_message.alphabets(xxx)

**Comment by vc-urvin** [comment]
Hello @emresasi,

Can you please share the exact scenario when you are facing this issue?

**Comment by emresasi** [comment]
After including it in my project that I am currently developing, after running php artisan db:audit and selecting the standard, I select the db I want to look at and this problem appears.
![Ekran görüntüsü 2024-05-30 131354](https://github.com/vcian/laravel-db-auditor/assets/6942826/394903f1-e52f-432f-815d-82a27fb75f78)

**Comment by vc-urvin** [comment]
Which versions of PHP, Laravel, and DB Auditor are you currently using?

**Comment by emresasi** [comment]
PHP 8.3.3-1
laravel 10
DB Auditor latest

**Comment by vc-urvin** [comment]
@emresasi - As per my analysis of this issue. You are using another language in your .env other than "EN", if this is the case than i suggest you can also generate the PR for another language. Path of the language folder - "src/Lang/en/"

**Comment by emresasi** [comment]
I don't believe it, so I'm sorry I bothered you.
