### ISSUE TITLE
Planned support for SQLite?

### ISSUE THREAD

**Issue by LukaszJaro** [vcian/laravel-db-auditor#50]

**Comment by ruchit288** [comment]
@LukaszJaro - Yes below databases are in our checklist.

1. PostgreSQL
2. SQLite

Also, We are open and Contributions are welcome to take this task and PR and will be fully credited.

Thanks.

**Comment by ruchit288** [comment]
@LukaszJaro 

Finally wait is over..

Now Laravel DB Auditor supports SQLite.  :)

**Comment by LukaszJaro** [comment]
You are too awesome, will try it out once I get some time, thanks!
